Repository maeve-jinjeon/airbnb, pull requests merged in 2022-06, with the labels that each got.

#13 feat : 달력 내 체크인, 체크아웃 및 초기화 이벤트 구현
  package-lock.json
  src/Component/Header/GNB/GNB.styled.tsx
  src/Component/Header/Modal/CalendarDetail/CalendarDetail.styled.tsx
  src/Component/Header/Modal/CalendarDetail/CalendarDetail.tsx
  src/Component/Header/Modal/Modal.tsx
  src/Component/Header/SearchBar/Guest/Guest.styled.tsx
  src/Component/Header/SearchBar/Guest/Guest.tsx
  src/Component/Header/SearchBar/Price/Price.styled.tsx
  src/Component/Header/SearchBar/Price/Price.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.styled.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.tsx
  src/Component/Header/SearchBar/SearchBar.styled.tsx
  src/Context/ScheduleContext.tsx
  src/Context/index.tsx
  src/Context/modalContext.tsx
  src/Styles/Normalize.jsx
  src/Styles/theme.js
  src/util/Icons.tsx
  src/util/util.tsx
Labels: feat, refactor, JinJeon, Maeve

#14 feat : mini-bar 일부 생성 및 checkin X버튼 적용
  src/Component/Header/Header.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.styled.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.tsx
  src/Component/Header/SearchBar/SmallSearchBar.styled.tsx
  src/Component/Header/SearchBar/SmallSearchBar.tsx
Labels: feat, JinJeon, Maeve

#15 fix : 기타 에러 수정
  src/Component/Header/Header.tsx
  src/Component/Header/Modal/CalendarDetail/CalendarDetail.tsx
  src/Component/Header/Modal/PriceDetail/PriceGraph/PriceRangeSlider/PriceRangeSlider.styled.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.tsx
  src/Context/ScheduleContext.tsx
Labels: fix, JinJeon, Maeve

#18 feat : 캘린더 슬라이더 구현
  src/Component/Header/Modal/CalendarDetail/Calendar/CalDayBox.tsx
  src/Component/Header/Modal/CalendarDetail/Calendar/CalTitle.tsx
  src/Component/Header/Modal/CalendarDetail/Calendar/Calendar.styled.tsx
  src/Component/Header/Modal/CalendarDetail/Calendar/Calendar.tsx
  src/Component/Header/Modal/CalendarDetail/Calendar/CalendarCell.tsx
  src/Component/Header/Modal/CalendarDetail/Calendar/CalendarDayBox.tsx
  src/Component/Header/Modal/CalendarDetail/Calendar/CalendarTitle.tsx
  src/Component/Header/Modal/CalendarDetail/CalendarDetail.styled.tsx
  src/Component/Header/Modal/CalendarDetail/CalendarDetail.tsx
  src/Component/Header/Modal/Modal.styled.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.tsx
  src/Styles/Normalize.jsx
  src/util/util.tsx
Labels: feat, refactor, fix, JinJeon, Maeve

#22 feat : 반응형 미니바 구현 및 모달 외부 클릭 시 창 닫기 기능 구현
  public/index.html
  src/App.tsx
  src/Component/Header/GNB/GNB.styled.tsx
  src/Component/Header/GNB/GNB.tsx
  src/Component/Header/Header.styled.tsx
  src/Component/Header/Header.tsx
  src/Component/Header/Modal/CalendarDetail/CalendarDetail.styled.tsx
  src/Component/Header/Modal/Modal.styled.tsx
  src/Component/Header/Modal/Modal.tsx
  src/Component/Header/Modal/Portal.js
  src/Component/Header/SearchBar/Guest/Guest.styled.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniGuest/MiniGuest.styled.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniGuest/MiniGuest.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniPrice/MiniPrice.styled.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniPrice/MiniPrice.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniSchedule/MiniSchedule.styled.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniSchedule/MiniSchedule.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniSearchBar.styled.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniSearchBar.tsx
  src/Component/Header/SearchBar/Price/Price.styled.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.styled.tsx
  src/Component/Header/SearchBar/SearchBar.styled.tsx
  src/Component/Header/SearchBar/SearchBar.tsx
  src/Component/Header/SearchBar/SmallSearchBar.styled.tsx
  src/Component/Header/SearchBar/SmallSearchBar.tsx
  src/Styles/theme.js
Labels: feat, refactor, fix, Maeve

#25 feat : 반응형 미니바 구현 완성
  src/App.tsx
  src/Component/Header/GNB/GNB.tsx
  src/Component/Header/Header.styled.tsx
  src/Component/Header/Header.tsx
  src/Component/Header/Modal/Modal.styled.tsx
  src/Component/Header/SearchBar/Guest/Guest.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniSearchBar.styled.tsx
  src/Component/Header/SearchBar/MiniSearchBar/MiniSearchBar.tsx
  src/Component/Header/SearchBar/Price/Price.tsx
  src/Component/Header/SearchBar/Schedule/Schedule.tsx
  src/Component/Header/SearchBar/SearchBar.styled.tsx
  src/Component/Header/SearchBar/SearchBar.tsx
  src/Component/SearchDesc/SearchDesc.styled.tsx
Labels: feat, refactor, fix, Maeve

#26 feat : 검색 결과 지도에 표시
  public/index.html
  src/Component/SearchDesc/SearchDesc.styled.tsx
  src/Component/SearchDesc/SearchDesc.tsx
  src/Component/SearchDesc/SearchLists.tsx
  src/Component/SearchDesc/SearchMap.tsx
  src/MockData/data.js
  src/Styles/theme.js
Labels: feat, JinJeon, Maeve
